### ISSUE TITLE
Release melodic, noetic

### ISSUE THREAD

**Issue by SteveMacenski** [ros-perception/perception_open3d#2]

**Comment by nkhedekar** [comment]
Just to confirm, both are to be released from the `main` branch? Also, running a release as per the first time release instructions (and in fact even in future releases) directly pushes to the `main` branch and creates a tag. I assume that's fine?

**Comment by SteveMacenski** [comment]
We should probably make a melodic-devel branch to then release instead. We shouldn't use `main` for releases. 

I don't know what you mean by directly pushes to main and creates a tag. I don't think anything in releasing should be pushing to the host branch (or I've been doing some stuff manually that others have automated)

**Comment by nkhedekar** [comment]
Agreed. There should be a `melodic-devel` and `noetic-devel` to release from. 

For the second point, the two commits are updating the changelog and pushing a tag (example here: https://github.com/unr-arl/open3d_ros/commits/melodic-devel)

**Comment by SteveMacenski** [comment]
For something this simple, I don't think you need both, one should be fine.

**Comment by nkhedekar** [comment]
very well, just `melodic-devel` then. And what about the second point?

**Comment by SteveMacenski** [comment]
Ah sure

**Comment by nkhedekar** [comment]
Released with bloom for melodic (https://github.com/ros/rosdistro/pull/25968) and noetic (https://github.com/ros/rosdistro/pull/25970) with pull request testing set to true

**Comment by SteveMacenski** [comment]
https://github.com/ros-perception/perception_open3d/blob/main/open3d_conversions/package.xml#L4 version doesn't match.

**Comment by nkhedekar** [comment]
Yep, as I understand it, catkin_prepare_release bumps the version in the branch used to release (Hence - https://github.com/ros-perception/perception_open3d/blob/3f96b3e764013f84b6001c146cb896aae1bf2724/open3d_conversions/package.xml#L4). So the version in main should be changed manually?

**Comment by SteveMacenski** [comment]
Yeah - lets keep that synced. Typically for software development we make changes on the main branch then cherry pick it to a distribution. So its good to keep main up to date so that when we pick things over it includes everything and main isn't "behind".

**Comment by nkhedekar** [comment]
For future releases, to make things absolutely clear, from which branch should catkin_generate_changelog and catkin_prepare_release be run?

**Comment by SteveMacenski** [comment]
Main. Then cherry pick that stuff over to the appropriate branches
