### ISSUE TITLE
Noetic release failing

### ISSUE THREAD

**Issue by SteveMacenski** [ros-perception/perception_open3d#9]
http://build.ros.org/job/Nbin_uF64__open3d_conversions__ubuntu_focal_amd64__binary/1/console

```

18:47:37   Could not find a package configuration file provided by "Open3D" with any
18:47:37   of the following names:
18:47:37 
18:47:37     Open3DConfig.cmake
18:47:37     open3d-config.cmake
```

Error is above, the biggest item is that open3D couldn't be found to build with @nkhedekar

**Comment by nkhedekar** [comment]
I think this requires Open3D to be released for C++ (https://github.com/intel-isl/Open3D/issues/2110)?

**Comment by SteveMacenski** [comment]
Yes, so all releases will fail, noetic / melodic / anything else. Those PRs should be reverted or we'll just be spammed with failed builds until then.

**Comment by nkhedekar** [comment]
I've closed the one for melodic. For noetic, since it was merged, should I open another pr that removes the change in the rosdistro yaml?

**Comment by SteveMacenski** [comment]
Yeah, you can also hit the 'revert' button on that PR and it'll auto open a PR to do that for you

**Comment by nkhedekar** [comment]
Done
